name: Dev Bot Jr

on:
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]
  # This also handles PR comments:
  issue_comment:
    types: created

jobs:
  dbjr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run Dev Bot Jr
      uses: DevBotJr/action-dbjr@main
